# Generated by Django 4.0.2 on 2022-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255, verbose_name='parametro')),
                ('value', models.CharField(max_length=255, verbose_name='valor')),
                ('unit', models.CharField(choices=[('Days', 'Days'), ('months', 'Months'), ('weeks', 'Weeks'), ('years', 'Years')], default='Days', max_length=255, verbose_name='unidad')),
            ],
        ),
    ]
