# Generated by Django 4.0.2 on 2022-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_config_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='unit',
            field=models.CharField(choices=[('dias', 'Dias'), ('meses', 'Meses'), ('semanas', 'Semanas'), ('annos', 'Annos')], default='dias', max_length=255, verbose_name='unidad'),
        ),
    ]
