# Generated by Django 4.0.2 on 2022-05-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_config_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='ConfigDate',
        ),
        migrations.AlterModelOptions(
            name='configdate',
            options={'verbose_name': 'configuracionfecha', 'verbose_name_plural': 'configuracionesfechas'},
        ),
    ]
