# Generated by Django 4.0.2 on 2022-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_rename_config_configdate_alter_configdate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdate',
            options={'verbose_name': 'configuracion_fecha', 'verbose_name_plural': 'configuraciones_Fechas'},
        ),
    ]
