# Generated by Django 4.0.2 on 2022-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_configdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Electrónico')),
                ('massage', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
        ),
    ]
