# Generated by Django 4.0.2 on 2022-06-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='massage',
            new_name='message',
        ),
    ]
