# Generated by Django 4.0.2 on 2022-06-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_rename_massage_contactform_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'contacto_mensaje', 'verbose_name_plural': 'contacto_mensajes'},
        ),
    ]
