# Generated by Django 4.0.2 on 2022-03-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('provincia', models.CharField(max_length=255, verbose_name='provincia')),
                ('estado', models.CharField(max_length=255, verbose_name='estado')),
                ('fecha_instalacion', models.DateField(verbose_name='fecha_instalacion')),
                ('latitud', models.CharField(max_length=255, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=255, verbose_name='longitud')),
            ],
        ),
    ]
