# Generated by Django 4.0.2 on 2022-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'verbose_name': 'estacion', 'verbose_name_plural': 'estaciones'},
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(max_length=50, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(max_length=50, verbose_name='longitud'),
        ),
    ]
