# Generated by Django 4.0.2 on 2022-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0007_alter_estacion_formato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCalamaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('temp_media', models.FloatField(verbose_name='Temperatura')),
                ('temp_max', models.FloatField(verbose_name='TMax')),
                ('temp_min', models.FloatField(verbose_name='TMin')),
                ('humedad', models.FloatField(verbose_name='Humedad')),
                ('h_r_max', models.FloatField(verbose_name='H_R Max')),
                ('h_m_min', models.FloatField(verbose_name='H_M Min')),
                ('precipitacion', models.FloatField(verbose_name='Precipitacion')),
                ('direccion', models.FloatField(verbose_name='Direccion')),
                ('velocidad', models.FloatField(verbose_name='Velocidad')),
            ],
        ),
    ]
