# Generated by Django 4.0.2 on 2022-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='unit',
            field=models.CharField(choices=[('días', 'Days'), ('meses', 'Months'), ('semanas', 'Weeks'), ('años', 'Years')], default='días', max_length=255, verbose_name='unidad'),
        ),
    ]
