# Generated by Django 4.0.2 on 2022-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_config_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='unit',
            field=models.CharField(choices=[('dias', 'Days'), ('meses', 'Months'), ('semanas', 'Weeks'), ('años', 'Years')], default='dias', max_length=255, verbose_name='unidad'),
        ),
    ]
