# Generated by Django 4.0.2 on 2022-03-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0002_alter_estacion_options_alter_estacion_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='longitud',
        ),
        migrations.CreateModel(
            name='EstacionCoordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=50, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=50, verbose_name='longitud')),
                ('formato', models.CharField(max_length=50, verbose_name='formato')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estacion.estacion')),
            ],
        ),
    ]
