# Generated by Django 4.0.2 on 2022-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0003_remove_estacion_latitud_remove_estacion_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='formato',
            field=models.CharField(default='dms', max_length=50, verbose_name='formato'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(default='', max_length=50, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(default='', max_length=50, verbose_name='longitud'),
        ),
        migrations.DeleteModel(
            name='EstacionCoordenadas',
        ),
    ]
