# Generated by Django 4.0.2 on 2022-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0004_estacion_formato_estacion_latitud_estacion_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='formato',
            field=models.CharField(max_length=50, verbose_name='formato'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.CharField(max_length=50, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.CharField(max_length=50, verbose_name='longitud'),
        ),
    ]
