# Generated by Django 4.0.2 on 2022-04-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estacion', '0010_alter_estacion_archivo_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosCalamaca',
        ),
    ]
