# Generated by Django 4.0.2 on 2022-06-08 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estacion', '0012_estacionsuscripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estacionsuscripcion',
            unique_together={('usuario', 'estacion')},
        ),
    ]
